/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TransferReviewImport } from './routes/transfer-review'
import { Route as TransferCompletedImport } from './routes/transfer-completed'
import { Route as TransferImport } from './routes/transfer'
import { Route as ProductionImport } from './routes/production'
import { Route as MarketplaceImport } from './routes/marketplace'
import { Route as CreateTokenSummaryImport } from './routes/create-token-summary'
import { Route as CreateTokenImport } from './routes/create-token'
import { Route as CreateOrderImport } from './routes/create-order'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const TransferReviewRoute = TransferReviewImport.update({
  path: '/transfer-review',
  getParentRoute: () => rootRoute,
} as any)

const TransferCompletedRoute = TransferCompletedImport.update({
  path: '/transfer-completed',
  getParentRoute: () => rootRoute,
} as any)

const TransferRoute = TransferImport.update({
  path: '/transfer',
  getParentRoute: () => rootRoute,
} as any)

const ProductionRoute = ProductionImport.update({
  path: '/production',
  getParentRoute: () => rootRoute,
} as any)

const MarketplaceRoute = MarketplaceImport.update({
  path: '/marketplace',
  getParentRoute: () => rootRoute,
} as any)

const CreateTokenSummaryRoute = CreateTokenSummaryImport.update({
  path: '/create-token-summary',
  getParentRoute: () => rootRoute,
} as any)

const CreateTokenRoute = CreateTokenImport.update({
  path: '/create-token',
  getParentRoute: () => rootRoute,
} as any)

const CreateOrderRoute = CreateOrderImport.update({
  path: '/create-order',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/create-order': {
      preLoaderRoute: typeof CreateOrderImport
      parentRoute: typeof rootRoute
    }
    '/create-token': {
      preLoaderRoute: typeof CreateTokenImport
      parentRoute: typeof rootRoute
    }
    '/create-token-summary': {
      preLoaderRoute: typeof CreateTokenSummaryImport
      parentRoute: typeof rootRoute
    }
    '/marketplace': {
      preLoaderRoute: typeof MarketplaceImport
      parentRoute: typeof rootRoute
    }
    '/production': {
      preLoaderRoute: typeof ProductionImport
      parentRoute: typeof rootRoute
    }
    '/transfer': {
      preLoaderRoute: typeof TransferImport
      parentRoute: typeof rootRoute
    }
    '/transfer-completed': {
      preLoaderRoute: typeof TransferCompletedImport
      parentRoute: typeof rootRoute
    }
    '/transfer-review': {
      preLoaderRoute: typeof TransferReviewImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  CreateOrderRoute,
  CreateTokenRoute,
  CreateTokenSummaryRoute,
  MarketplaceRoute,
  ProductionRoute,
  TransferRoute,
  TransferCompletedRoute,
  TransferReviewRoute,
])

/* prettier-ignore-end */
